# *Урок 5*

# Списковые включения (list comprehensions)

In [14]:
# преобразование списка из строк в список из чисел
str_list = ["1", "5", "12", "7"]

int_list = [int(s) for s in str_list] 
#квадратные скобки указывают на создание списка

print(str_list)
print(int_list)

['1', '5', '12', '7']
[1, 5, 12, 7]


In [15]:
# все элементы списка возведены в квадрат, исходный список не изменился
[x**2 for x in int_list]

[1, 25, 144, 49]

In [16]:
# к каждому элементу прибавлена единица, исходный список не изменился
[x+1 for x in int_list]

[2, 6, 13, 8]

In [17]:
#отобраны элементы, превышающие 6
[x for x in int_list if x > 6]

[12, 7]

In [18]:
#есть два списка с числами, нужно найти их поэлементную сумму
X = [2, 5, 8]
Y = [1, 3, 100]

[x + y for x, y in zip(X, Y)]

[3, 8, 108]

In [19]:
#создание словаря
squared = {i: i**2 for i in range(10)} # используются фигурные скобки
squared

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [20]:
#создание списков
a = [0 for i in range(5)] #список из пяти нулей
print(a)

from random import randrange #список, заполненный случайными числами от 1 до 100 
n = 10
b = [randrange(1, 101) for r in range(n)]
print(b)


[0, 0, 0, 0, 0]
[68, 49, 20, 44, 16, 75, 73, 11, 69, 77]


# Задание 1

Написать функцию `sumprod(u, v)`, принимающую на вход два списка и вычисляющая сумму попарных произведений их элементов. Например, `sumprod([1, 2, 3], [4, 5, 6])` должен вернуть результат вычисления `1 * 4 + 2 * 5 + 3 * 6`, то есть 32. Использовать списковые включения.

In [21]:
# здесь записать решение задания 1
def sumprod(u, v):
    return sum([x*y for x, y in zip(u, v)])
sumprod([1, 2, 3], [4, 5, 6])

32

# Сортировка

In [22]:
my_list = [6, 9, 2, 7, 12, 8]
print(my_list)
my_list.sort() #ничего не возвращает, но меняет сам список
print(my_list)

[6, 9, 2, 7, 12, 8]
[2, 6, 7, 8, 9, 12]


In [23]:
my_list = [6, 9, 2, 7, 12, 8]
sorted_list = sorted(my_list) #не меняет исходный список
print(my_list)
print(sorted_list)

[6, 9, 2, 7, 12, 8]
[2, 6, 7, 8, 9, 12]


In [24]:
# сортировка строк
"abcd"<"b"

True

In [25]:
"abcd" < "addd" # первая буква совпадает, сравниваем вторую

True

In [26]:
"a" < "aa"

True

In [27]:
str_list = ["Bob", "Alice", "Bill", "Weigu"]
str_list.sort()
str_list

['Alice', 'Bill', 'Bob', 'Weigu']

In [28]:
my_tuple = (7, 1, 2, 6)
print (sorted(my_tuple)) # можно применять к кортежам, на выходе получается список

[1, 2, 6, 7]


In [29]:
sorted([4, 8, 1, 7], reverse=True) #сортировка в обратном порядке

[8, 7, 4, 1]

In [30]:
('a', 8) < ('b', 7) #сначала сравниваются первые элементы

True

In [31]:
('a', 8) < ('a', 7) #если первый элемент совпал, то сравниваются вторые элементы

False

In [32]:
#сортировка списка кортежей
names = [("Bob", 8, 4, 9),
         ("Alice", 7, 8, 9), 
         ("Weigu", 7, 5, 3), 
         ("Dan", 6, 4, 3)]

names.sort()
print(names)

[('Alice', 7, 8, 9), ('Bob', 8, 4, 9), ('Dan', 6, 4, 3), ('Weigu', 7, 5, 3)]


In [33]:
#сортировка по второму элементу кортежа
from operator import itemgetter
sorted(names, key=itemgetter(2))

[('Bob', 8, 4, 9), ('Dan', 6, 4, 3), ('Weigu', 7, 5, 3), ('Alice', 7, 8, 9)]

# Задание 2

Написать функцию `first_str(words)`, принимающую на вход список строк и возвращающую ту из них, которая будет идти первой при упорядочивании по алфавиту. Использовать библиотеки нельзя.

In [34]:
# здесь записать решение задания 2
def first_str(words):
    return sorted(words)[0]
first_str(['a', 'b', 'c'])

'a'

# Задание 3

Написать функцию `get_first_student_grade(students)`, принимающую на вход список `students`, каждый элемент которого является кортежем: первый элемент кортежа является именем студента, а второй его оценкой. Например: `students = [('Bob', 3), ('Alice', 4)]`. Функция должна вернуть оценку студента, имя которого является первым при алфавитной сортировке. (В нашем случае должна вернуть число `4`.) Все студенты имеют разные имена. Использовать библиотеки нельзя.

In [35]:
# здесь записать решение задания 3
def get_first_student_grade(students):
    return sorted(students, key = lambda x: x[0])[0][1]
get_first_student_grade([('Bob', 3), ('Alice', 4)])

4

# Задание 4

Написать функцию `get_name_of_best_student(students)`, принимающую на вход список `students`, каждый элемент которого является кортежем: первый элемент кортежа является именем студента, а второй его оценкой. Например: `students = [('Bob', 3), ('Alice', 4)]`. Функция должна вернуть имя студента с наибольшей оценкой. Если таких студентов несколько, она должна вернуть имя того из них, кто первый встречается в списке `students` (в том порядке, в котором этот список передан). Например, для списка `[('Bob', 4), ('Alice', 4)]` необходимо вернуть `'Bob'`, а для списка `[('Alice', 4), ('Bob', 4)]` вернуть `'Alice'`. Задачу можно решить без циклов и условных операторов.

In [81]:
# здесь записать решение задания 4
def get_name_of_best_student(students):
    students.reverse()
    students = sorted(students, key = lambda x: x[1])
    return students[-1][0]
get_name_of_best_student([('Bob', 3), ('Alice', 4)])

'Alice'

# Задание 5 (необязательное)
Написать функцию `sort_by_last_first_name(names)`, которая на вход принимает список строк с именами и фамилиями, сортирующую его по фамилии, а при совпадении фамилий — по именам, и возвращающую в отсортированном виде. (Можно менять исходный список.) Например, для списка `["Alice Smith", "John Doe", "Jack Doe"]` должно быть возвращено `["Jack Doe", "John Doe", "Alice Smith"]`.

In [37]:
# здесь записать решение задания 5

# Библиотека numpy

Ускоряет и упрощает работу с числами. Главный объект, с которым мы будем работать — это np.array. Практически все операции для массива выполняются поэлементно.

In [38]:
numbers = [1.2] * 100
print(numbers)

[1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2]


In [39]:
import numpy as np
np_numbers = np.array(numbers) # преобразуем список в массив
# np.array — это специальный тип данных, похожий на список, но содержащий данные только одного типа
np_numbers

array([1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2])

In [40]:
type(np_numbers)

numpy.ndarray

In [41]:
np_numbers[3] 

1.2

In [42]:
len(np_numbers)

100

In [43]:
np_squares = np_numbers**2
np_squares

array([1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44, 1.44,
       1.44])

In [44]:
from numpy import array
# чтобы не писать каждый раз np

In [45]:
q = array([4, 5, 8, 9])
q[0]
q[2]
# можно обращаться к элементам массива по индексам, как и к спискам

8

In [46]:
q[0] = 12 #меняются элементы также
q

array([12,  5,  8,  9])

In [47]:
q[1:3] #можно делать срезы

array([5, 8])

In [48]:
q = array([4, 5, 8, 9])
w = array([2, 3, 6, 10])
q + w
#арифметические операции над массивами выполняются поэлементно

array([ 6,  8, 14, 19])

In [49]:
np.concatenate( [q, w] )
# для конкатенации

array([ 4,  5,  8,  9,  2,  3,  6, 10])

In [50]:
q*w #перемножение элементов

array([ 8, 15, 48, 90])

In [51]:
q = np.array([14, 8, 14, 9])
w = np.array([1, 3, 4])
q + w # если у массивов разная длина, то ничего не получится

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [52]:
x = array([1,2,3,4,5])
np.sqrt(x) # используем функцию sqrt из numpy

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [53]:
import math
math.sqrt(x) #аналогичная функция из math не работает

TypeError: only size-1 arrays can be converted to Python scalars

In [54]:
mixed_array = np.array([1, True, 3, "Hello"])
# в массивах могут храниться не только числа, но все элементы, лежащие в одном массиве, должны быть одного типа
print(mixed_array)
# Числа 1, 2, 3 превратились в строчки '1', '2', '3'. 

['1' 'True' '3' 'Hello']


In [55]:
np.array([1,True,3, 5.])
#все числа превратились в вещественные

array([1., 1., 3., 5.])

In [56]:
y = x.copy() #создать копию массива
y

array([1, 2, 3, 4, 5])

In [57]:
x = array([1.1, 2.2, 3.3, 4.4, 5.5])
y = x[ [1, 3, 4] ] # создать новый массив на основе выбранных элементов существующего
y

array([2.2, 4.4, 5.5])

In [ ]:
x = array([1.1, 2.2, 3.3, 4.4, 5.5])
y = x[ x < 4 ] # создать новый массив на основе элементов, которые меньше 4
y

In [ ]:
x < 4 #проверка соотвествия элементов условию

In [ ]:
x = array([1.1, 2.2, 3.3, 4.4, 5.5, 30.3, 45.3, 56.7])
y = x[ (x < 50) & (x >3) ] # можно использовать несколько условий
y

# Задание 6
Написать функцию `double_this(arr)`, принимающую на вход массив `arr`, состоящий из чисел, и возвращающую массив, полученный удвоением каждого элемента `arr`.

In [60]:
# здесь записать решение задания 6
def double_this(arr):
    return arr*2
double_this(np.array([1, 2, 3]))

array([2, 4, 6])

# Задание 7
Написать функцию `select_even(arr)`, принимающую на вход массив целых чисел `arr` и возвращающую новый массив, который состоит из всех *чётных* элементов `arr`.

In [64]:
# здесь записать решение задания 7
def select_even(arr):
    return arr[(arr %2 == 0)]
select_even(np.array([1, 2, 3, 4]))

array([2, 4])

# Задание 8

In [66]:
# рост баскетболистов в дюймах
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]
# вес баскетболистов в фунтах
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

# преобразуйте списоки в массивы и далее работайте только с массивами
height = np.array(height_in)
weight = np.array(weight_lb)
# переведите рост в метры, вес в килограммы 
# рассчитайте индекс массы тела (ИМТ) для каждого баскетболиста
# создайте новый массив, содержащий ИМТ из баскетболистов, у которых значение ИМТ < 21

In [69]:
height = height * 0.02
display(height)
weight = weight * 2.2 
display(height)

array([0.00075184, 0.00075184, 0.00073152, ..., 0.000762  , 0.000762  ,
       0.00074168])

array([0.00075184, 0.00075184, 0.00073152, ..., 0.000762  , 0.000762  ,
       0.00074168])

In [74]:
IMT  = weight/ (height **2) 
display(IMT)

array([1.54122843e+09, 1.84091174e+09, 1.89938169e+09, ...,
       1.70879231e+09, 1.58375872e+09, 1.71572167e+09])

In [78]:
x = IMT[(IMT < 21)]
x

array([], dtype=float64)

# Задание 9 (необязательное)
Написать функцию `wipe_even(arr, target_value, in_place)`, принимающую на вход массив целых чисел `arr`, и возвращающую массив, полученный из `arr` путём замены всех чётных элементов на  `target_value`. Если `target_value` не указано, то оно должно считаться равным числу 0. Если указан параметр `in_place` и он равен `True`, то функция должна менять исходный массив, а если не указан или указан в `False`, то нужно создать копию исходного массива и менять эту копию, так, чтобы сам исходный массив остался неизменным.

In [ ]:
# здесь записать решение задания 9

# Задание 10 (необязательное)
Написать функцию `mean_by_gender(grades, genders)`, принимающую на вход два массива одинаковой длины: в массиве `grades` записаны оценки некоторых студентов, а в массиве `genders` — их пол в виде строк `male` или `female`. Требуется вернуть словарь, ключами которого будут строки `male` и `female`, а записями — среднее арифметическое оценок студентов соответствующего пола.

Например, если `grades = np.array([5, 4, 3, 5, 2])` и `genders = np.array(["female", "male", "male", "female", "male"])`, функция должна вернуть словарь `{'male': 3.0, 'female': 5.0}`.

In [ ]:
# здесь записать решение задания 10

_Источники pythontutor.ru, math-info.hse.ru, datacamp.com_